site_name: Cloudbreak 1.2.1
site_url: http://sequenceiq.com/cloudbreak-docs
repo_url: https://github.com/sequenceiq/cloudbreak-docs
theme: mkdocs
theme_dir: mkdocs_theme
dev_addr: 0.0.0.0:8000
markdown_extensions:
    - markdown_include.include
pages:
    - Home:
        - Introduction : index.md
        - Architecture : architecture.md
        - Installation : onprem.md
        - Release Notes : releasenotes.md
        - Change Log : changelog.md
    - AWS: aws.md
    - Azure : azure.md
    - GCP : gcp.md
    - OpenStack : openstack.md
    - Reference:
        - API : api.md
        - CLI/Shell : shell.md
        - Account Management: ui_account.md
        - Auto-Scaling : periscope.md
        - SSSD Configuration: sssd.md
        - Recipes: recipes.md
        - Blueprints : blueprints.md
        - Platforms : topologies.md
        - Kerberos: kerberos.md
        - Mesos: mesos.md
        - SPI: spi.md
        - Operations : operations.md
        - Migration : database.md
        - Advanced Configuration : configuration.md
        - Development :
            - Environments : environments.md
            - Flows : flow.html
        - Known issues: issues.md